# Generated by Django 2.1.7 on 2019-04-20 08:00

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import zantapp.models


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0009_alter_user_last_name_max_length'),
        ('zantapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('first_name', models.CharField(blank=True, max_length=30, verbose_name='first name')),
                ('last_name', models.CharField(blank=True, max_length=150, verbose_name='last name')),
                ('is_staff', models.BooleanField(default=False, help_text='Designates whether the user can log into this admin site.', verbose_name='staff status')),
                ('is_active', models.BooleanField(default=True, help_text='Designates whether this user should be treated as active. Unselect this instead of deleting accounts.', verbose_name='active')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined')),
                ('id', models.CharField(default=zantapp.models.id_gen, editable=False, max_length=10, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='created time')),
                ('updated_at', models.DateTimeField(auto_now=True, db_index=True, verbose_name='updated time')),
                ('email', models.EmailField(max_length=255, unique=True, verbose_name='email address')),
                ('is_seeker', models.BooleanField(default=False, verbose_name='seeker')),
                ('is_employer', models.BooleanField(default=False, verbose_name='employer')),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.Group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.Permission', verbose_name='user permissions')),
            ],
            options={
                'verbose_name': 'user',
                'verbose_name_plural': 'users',
            },
            managers=[
                ('objects', zantapp.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name='Employer',
            fields=[
                ('id', models.CharField(default=zantapp.models.id_gen, editable=False, max_length=10, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='created time')),
                ('updated_at', models.DateTimeField(auto_now=True, db_index=True, verbose_name='updated time')),
                ('photo', models.URLField(blank=True, max_length=500)),
                ('summary', models.CharField(blank=True, max_length=500, verbose_name='summary')),
                ('confirm_spending', models.BooleanField(default=False)),
                ('credits', models.IntegerField(default=0)),
                ('company_name', models.CharField(blank=True, max_length=100, verbose_name='company name')),
                ('free_calls', models.IntegerField(default=0)),
                ('postings', models.IntegerField(default=1)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='employer', to=settings.AUTH_USER_MODEL, verbose_name='user')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Seeker',
            fields=[
                ('id', models.CharField(default=zantapp.models.id_gen, editable=False, max_length=10, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='created time')),
                ('updated_at', models.DateTimeField(auto_now=True, db_index=True, verbose_name='updated time')),
                ('photo', models.URLField(blank=True, max_length=500)),
                ('summary', models.CharField(blank=True, max_length=500, verbose_name='summary')),
                ('confirm_spending', models.BooleanField(default=False)),
                ('credits', models.IntegerField(default=0)),
                ('desired_title', models.CharField(blank=True, max_length=150, verbose_name='desired title')),
                ('top_skills', zantapp.models.SkillsField(base_field=models.CharField(max_length=30), blank=True, default=list, size=5)),
                ('extra_skills', zantapp.models.SkillsField(base_field=models.CharField(max_length=30), blank=True, default=list, size=None)),
                ('other_skills', zantapp.models.SkillsField(base_field=models.CharField(max_length=30), blank=True, default=list, size=None)),
                ('experience', models.CharField(blank=True, max_length=10000)),
                ('education', models.CharField(blank=True, max_length=10000)),
                ('free_apps', models.IntegerField(default=5)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='seeker', to=settings.AUTH_USER_MODEL, verbose_name='user')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.DeleteModel(
            name='Profile',
        ),
    ]
