# Generated by Django 2.1.7 on 2019-04-25 18:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('zantapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='email',
            field=models.EmailField(max_length=255, unique=True, verbose_name='email address'),
        ),
        migrations.AlterField(
            model_name='user',
            name='username',
            field=models.CharField(blank=True, default='', max_length=255, verbose_name='Username'),
        ),
    ]
