# Generated by Django 2.2.1 on 2019-05-17 21:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('zantapp', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='guest',
            name='invitation',
        ),
        migrations.RemoveField(
            model_name='invitation',
            name='date',
        ),
        migrations.RemoveField(
            model_name='invitation',
            name='description',
        ),
        migrations.RemoveField(
            model_name='invitation',
            name='headline',
        ),
        migrations.RemoveField(
            model_name='invitation',
            name='location',
        ),
        migrations.RemoveField(
            model_name='invitation',
            name='type',
        ),
        migrations.RemoveField(
            model_name='invitation',
            name='url',
        ),
        migrations.RemoveField(
            model_name='invitation',
            name='user',
        ),
        migrations.AlterField(
            model_name='guest',
            name='friend_of',
            field=models.CharField(choices=[('one', 'two')], max_length=50),
        ),
    ]
