# Generated by Django 2.2 on 2019-05-14 22:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('zantapp', '0002_auto_20190425_1809'),
    ]

    operations = [
        migrations.AlterField(
            model_name='client',
            name='partner_one_gender',
            field=models.CharField(choices=[('m', 'male'), ('f', 'female')], max_length=50),
        ),
        migrations.AlterField(
            model_name='client',
            name='wedding_date',
            field=models.DateField(auto_now_add=True, db_index=True, verbose_name='wedding date'),
        ),
    ]
