# Generated by Django 2.2.1 on 2019-05-17 21:39

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('zantapp', '0002_auto_20190517_1438'),
    ]

    operations = [
        migrations.AddField(
            model_name='guest',
            name='invitation',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='zantapp.Invitation', verbose_name='Invitation id'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='invitation',
            name='date',
            field=models.DateField(auto_now_add=True, db_index=True, default=django.utils.timezone.now, verbose_name='date'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='invitation',
            name='description',
            field=models.CharField(blank=True, max_length=5000),
        ),
        migrations.AddField(
            model_name='invitation',
            name='headline',
            field=models.CharField(blank=True, max_length=5000),
        ),
        migrations.AddField(
            model_name='invitation',
            name='location',
            field=models.CharField(blank=True, max_length=5000),
        ),
        migrations.AddField(
            model_name='invitation',
            name='type',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='zantapp.Services', verbose_name='Service Type'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='invitation',
            name='url',
            field=models.URLField(blank=True),
        ),
        migrations.AddField(
            model_name='invitation',
            name='user',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='zantapp.Client', verbose_name='Client id'),
            preserve_default=False,
        ),
    ]
