# Generated by Django 2.2.1 on 2019-05-17 21:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('zantapp', '0003_auto_20190517_1439'),
    ]

    operations = [
        migrations.AlterField(
            model_name='invitation',
            name='date',
            field=models.DateField(auto_now=True, db_index=True, verbose_name='date'),
        ),
    ]
