# Generated by Django 2.2 on 2019-05-14 22:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('zantapp', '0003_auto_20190514_1506'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='username',
        ),
    ]
